In [1]:
conda install pandas numpy matplotlib seaborn scikit-learn

Jupyter detected...
2 channel Terms of Service accepted
doneieving notices: -
Channels:
 - defaults
Platform: osx-arm64
doneecting package metadata (repodata.json): \
doneing environment: \

# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [3]:
df= pd.read_csv('/Users/ashikjavij/Downloads/dataset1.csv')
df.head()

  Policy no.  age  gender     bmi  charges in INR
0  PLC156898   19  female  27.900     16884.92400
1  PLC156907   18    male  33.770      1725.55230
2  PLC156916   28    male  33.000      4449.46200
3  PLC156925   33    male  22.705     21984.47061
4  PLC156934   32    male  28.880      3866.85520

In [5]:
df.tail()

<bound method NDFrame.tail of      Policy no.  age  gender     bmi  charges in INR
0     PLC156898   19  female  27.900     16884.92400
1     PLC156907   18    male  33.770      1725.55230
2     PLC156916   28    male  33.000      4449.46200
3     PLC156925   33    male  22.705     21984.47061
4     PLC156934   32    male  28.880      3866.85520
...         ...  ...     ...     ...             ...
1333  PLC168895   50    male  30.970     10600.54830
1334  PLC168904   18  female  31.920      2205.98080
1335  PLC168913   18  female  36.850      1629.83350
1336  PLC168922   21  female  25.800      2007.94500
1337  PLC168931   61  female  29.070     29141.36030

[1338 rows x 5 columns]>

In [6]:
df.tail()

     Policy no.  age  gender    bmi  charges in INR
1333  PLC168895   50    male  30.97      10600.5483
1334  PLC168904   18  female  31.92       2205.9808
1335  PLC168913   18  female  36.85       1629.8335
1336  PLC168922   21  female  25.80       2007.9450
1337  PLC168931   61  female  29.07      29141.3603

In [7]:
df.shape #To find out the total rows n cols in a dataset

(1338, 5)

In [8]:
df.columns #Display the column names in the data frame

Index(['Policy no.', 'age', 'gender', 'bmi', 'charges in INR'], dtype='object')

In [9]:
df.dtypes #Display the type of object

Policy no.         object
age                 int64
gender             object
bmi               float64
charges in INR    float64
dtype: object

In [10]:
df.info #Display the total information of the dataset

<bound method DataFrame.info of      Policy no.  age  gender     bmi  charges in INR
0     PLC156898   19  female  27.900     16884.92400
1     PLC156907   18    male  33.770      1725.55230
2     PLC156916   28    male  33.000      4449.46200
3     PLC156925   33    male  22.705     21984.47061
4     PLC156934   32    male  28.880      3866.85520
...         ...  ...     ...     ...             ...
1333  PLC168895   50    male  30.970     10600.54830
1334  PLC168904   18  female  31.920      2205.98080
1335  PLC168913   18  female  36.850      1629.83350
1336  PLC168922   21  female  25.800      2007.94500
1337  PLC168931   61  female  29.070     29141.36030

[1338 rows x 5 columns]>

In [11]:
df.head(11)

   Policy no.  age  gender     bmi  charges in INR
0   PLC156898   19  female  27.900     16884.92400
1   PLC156907   18    male  33.770      1725.55230
2   PLC156916   28    male  33.000      4449.46200
3   PLC156925   33    male  22.705     21984.47061
4   PLC156934   32    male  28.880      3866.85520
5   PLC156943   31  female  25.740      3756.62160
6   PLC156952   46  female  33.440      8240.58960
7   PLC156961   37  female  27.740      7281.50560
8   PLC156970   37    male  29.830      6406.41070
9   PLC156979   60  female  25.840     28923.13692
10  PLC156988   25    male  26.220      2721.32080

In [12]:
df.drop('gender',axis=1)

     Policy no.  age     bmi  charges in INR
0     PLC156898   19  27.900     16884.92400
1     PLC156907   18  33.770      1725.55230
2     PLC156916   28  33.000      4449.46200
3     PLC156925   33  22.705     21984.47061
4     PLC156934   32  28.880      3866.85520
...         ...  ...     ...             ...
1333  PLC168895   50  30.970     10600.54830
1334  PLC168904   18  31.920      2205.98080
1335  PLC168913   18  36.850      1629.83350
1336  PLC168922   21  25.800      2007.94500
1337  PLC168931   61  29.070     29141.36030

[1338 rows x 4 columns]

In [13]:
#Null values identification 
df.isna()

      Policy no.    age  gender    bmi  charges in INR
0          False  False   False  False           False
1          False  False   False  False           False
2          False  False   False  False           False
3          False  False   False  False           False
4          False  False   False  False           False
...          ...    ...     ...    ...             ...
1333       False  False   False  False           False
1334       False  False   False  False           False
1335       False  False   False  False           False
1336       False  False   False  False           False
1337       False  False   False  False           False

[1338 rows x 5 columns]

In [14]:
#Null Values Identification - Not Available/ Applicable
df.isna().sum() #sum, for summarising the output

Policy no.        0
age               0
gender            0
bmi               0
charges in INR    0
dtype: int64

In [15]:
df.isnull().sum()

Policy no.        0
age               0
gender            0
bmi               0
charges in INR    0
dtype: int64

In [16]:
#if the na/null values are,present, to drop them 
df.dropna(inplace=True)

In [17]:
df.isnull().sum()

Policy no.        0
age               0
gender            0
bmi               0
charges in INR    0
dtype: int64

In [18]:
#Finding unique values for cols in df 
df['gender'].unique()

array(['female', 'male'], dtype=object)

In [19]:
#To count the individual unique value #To count the individual cols row length
df['gender'].count()

np.int64(1338)

In [20]:
#To count the individual unique values
df[df['gender']=='female']['gender'].count()

np.int64(662)

In [21]:
#to count the individual unique values
df[df['gender']=='male']['gender'].count()

np.int64(676)

In [22]:
df['gender'].value_counts()

gender
male      676
female    662
Name: count, dtype: int64

In [23]:
df['age'].value_counts()

age
18    69
19    68
50    29
51    29
47    29
46    29
45    29
20    29
48    29
52    29
22    28
49    28
54    28
53    28
21    28
26    28
24    28
25    28
28    28
27    28
23    28
43    27
29    27
30    27
41    27
42    27
44    27
31    27
40    27
32    26
33    26
56    26
34    26
55    26
57    26
37    25
59    25
58    25
36    25
38    25
35    25
39    25
61    23
60    23
63    23
62    23
64    22
Name: count, dtype: int64

In [24]:
#To perform descriptive statistics in the data set 
df.describe()

               age          bmi  charges in INR
count  1338.000000  1338.000000     1338.000000
mean     39.207025    30.663397    13270.422265
std      14.049960     6.098187    12110.011237
min      18.000000    15.960000     1121.873900
25%      27.000000    26.296250     4740.287150
50%      39.000000    30.400000     9382.033000
75%      51.000000    34.693750    16639.912515
max      64.000000    53.130000    63770.428010

In [25]:
#Merge function - to marge two data frames
df.head()

  Policy no.  age  gender     bmi  charges in INR
0  PLC156898   19  female  27.900     16884.92400
1  PLC156907   18    male  33.770      1725.55230
2  PLC156916   28    male  33.000      4449.46200
3  PLC156925   33    male  22.705     21984.47061
4  PLC156934   32    male  28.880      3866.85520

In [26]:
df1 =pd.read_excel('/Users/ashikjavij/Downloads/dataset 2.xlsx')
df1.head()

  Policy no.  children smoker     region
0  PLC157006         0     no  southwest
1  PLC157033         1     no  southwest
2  PLC157060         0     no  southwest
3  PLC157087         1     no  southwest
4  PLC157186         5     no  southwest

In [27]:
#if the na/null values are,present, to drop them 
df1.dropna(inplace=True)

In [28]:
#Mergeing datasets
new_df = pd.merge(df,df1, on='Policy no.')
new_df.head()

  Policy no.  age  gender     bmi  charges in INR  children smoker     region
0  PLC156898   19  female  27.900     16884.92400         0    yes  southwest
1  PLC156907   18    male  33.770      1725.55230         1     no  southeast
2  PLC156916   28    male  33.000      4449.46200         3     no  southeast
3  PLC156925   33    male  22.705     21984.47061         0     no  northwest
4  PLC156934   32    male  28.880      3866.85520         0     no  northwest

In [29]:
df1.shape

(1338, 4)

In [30]:
new_df.shape

(1338, 8)

In [31]:
#Group by Function in pandas
new_df.head()

  Policy no.  age  gender     bmi  charges in INR  children smoker     region
0  PLC156898   19  female  27.900     16884.92400         0    yes  southwest
1  PLC156907   18    male  33.770      1725.55230         1     no  southeast
2  PLC156916   28    male  33.000      4449.46200         3     no  southeast
3  PLC156925   33    male  22.705     21984.47061         0     no  northwest
4  PLC156934   32    male  28.880      3866.85520         0     no  northwest

In [32]:
nc = ['age','bmi','charges in INR','children']
new_df.groupby('gender')[nc].mean()

              age        bmi  charges in INR  children
gender
female  39.503021  30.377749    12569.578844  1.074018
male    38.917160  30.943129    13956.751178  1.115385

In [33]:
#find the total charges in spend by male and femal
#total charges incurrred by male and female
a= ['charges in INR']
new_df.groupby('gender')[a].sum()

        charges in INR
gender
female    8.321061e+06
male      9.434764e+06

In [34]:
new_df.groupby('gender')['charges in INR'].sum()

gender
female    8.321061e+06
male      9.434764e+06
Name: charges in INR, dtype: float64